# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'knn.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ML(object):
    def setupUi(self, ML):
        ML.setObjectName("ML")
        ML.resize(392, 431)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons8-linux-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ML.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ML)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_mode_state = QtWidgets.QLabel(self.centralwidget)
        self.label_mode_state.setObjectName("label_mode_state")
        self.gridLayout.addWidget(self.label_mode_state, 0, 0, 1, 1)
        self.lineEdit_feature = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_feature.setObjectName("lineEdit_feature")
        self.gridLayout.addWidget(self.lineEdit_feature, 1, 1, 1, 1)
        self.lineEdit_target = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target.setEnabled(False)
        self.lineEdit_target.setObjectName("lineEdit_target")
        self.gridLayout.addWidget(self.lineEdit_target, 2, 1, 1, 1)
        self.label_target = QtWidgets.QLabel(self.centralwidget)
        self.label_target.setAlignment(QtCore.Qt.AlignCenter)
        self.label_target.setObjectName("label_target")
        self.gridLayout.addWidget(self.label_target, 2, 0, 1, 1)
        self.pushButton_predict = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.gridLayout.addWidget(self.pushButton_predict, 1, 2, 1, 1)
        self.label_feature = QtWidgets.QLabel(self.centralwidget)
        self.label_feature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feature.setObjectName("label_feature")
        self.gridLayout.addWidget(self.label_feature, 1, 0, 1, 1)
        self.lineEdit_model_state = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_model_state.setEnabled(False)
        self.lineEdit_model_state.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_model_state.setObjectName("lineEdit_model_state")
        self.gridLayout.addWidget(self.lineEdit_model_state, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_figure = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_figure.setObjectName("comboBox_figure")
        self.horizontalLayout.addWidget(self.comboBox_figure)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_figure = QtWidgets.QVBoxLayout()
        self.verticalLayout_figure.setObjectName("verticalLayout_figure")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_figure.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_figure)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        ML.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ML)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ML.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ML)
        self.statusbar.setObjectName("statusbar")
        ML.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(ML)
        self.actionLoad.setObjectName("actionLoad")
        self.actionQuit = QtWidgets.QAction(ML)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTrain = QtWidgets.QAction(ML)
        self.actionTrain.setObjectName("actionTrain")
        self.menuFile.addAction(self.actionTrain)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ML)
        self.actionQuit.triggered.connect(ML.close)
        QtCore.QMetaObject.connectSlotsByName(ML)

    def retranslateUi(self, ML):
        _translate = QtCore.QCoreApplication.translate
        ML.setWindowTitle(_translate("ML", "ML"))
        self.label_mode_state.setText(_translate("ML", "Model State"))
        self.label_target.setText(_translate("ML", "Target:"))
        self.pushButton_predict.setText(_translate("ML", "Predict"))
        self.label_feature.setText(_translate("ML", "Feature:"))
        self.lineEdit_model_state.setText(_translate("ML", "Wait for loading"))
        self.label.setText(_translate("ML", "Figure Type:"))
        self.menuFile.setTitle(_translate("ML", "File"))
        self.actionLoad.setText(_translate("ML", "Load"))
        self.actionQuit.setText(_translate("ML", "Quit"))
        self.actionQuit.setShortcut(_translate("ML", "Ctrl+Q"))
        self.actionTrain.setText(_translate("ML", "Train"))

