from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from xuexiaolei.python.tf_practice.iris.SourceCode.config.config import ConfigPath


class TrainModel_ui(QDialog):
    def setupUi(self):
        self.setObjectName("Dialog")
        self.setWindowModality(QtCore.Qt.ApplicationModal)
        self.resize(319, 144)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(ConfigPath.WindowsIcon.value), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_model_type = QtWidgets.QLabel(self)
        self.label_model_type.setObjectName("label_model_type")
        self.horizontalLayout_2.addWidget(self.label_model_type)
        self.comboBox_model_type = QtWidgets.QComboBox(self)
        self.comboBox_model_type.setObjectName("comboBox_model_type")
        self.horizontalLayout_2.addWidget(self.comboBox_model_type)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_param = QtWidgets.QLabel(self)
        self.label_param.setAlignment(QtCore.Qt.AlignCenter)
        self.label_param.setObjectName("label_param")
        self.gridLayout.addWidget(self.label_param, 1, 0, 1, 1)
        self.lineEdit_param = QtWidgets.QLineEdit(self)
        self.lineEdit_param.setObjectName("lineEdit_param")
        self.gridLayout.addWidget(self.lineEdit_param, 1, 1, 1, 1)
        self.lineEdit_data = QtWidgets.QLineEdit(self)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout.addWidget(self.lineEdit_data, 0, 1, 1, 1)
        self.toolButton_choosedata = QtWidgets.QToolButton(self)
        self.toolButton_choosedata.setObjectName("toolButton_choosedata")
        self.gridLayout.addWidget(self.toolButton_choosedata, 0, 2, 1, 1)
        self.label_data = QtWidgets.QLabel(self)
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.gridLayout.addWidget(self.label_data, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_predict = QtWidgets.QPushButton(self)
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.horizontalLayout.addWidget(self.pushButton_predict)
        self.pushButton_save_model = QtWidgets.QPushButton(self)
        self.pushButton_save_model.setObjectName("pushButton_save_model")
        self.horizontalLayout.addWidget(self.pushButton_save_model)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog_train_model"))
        self.label_model_type.setText(_translate("Dialog", "Model Type:"))
        self.label_param.setText(_translate("Dialog", "Param"))
        self.toolButton_choosedata.setText(_translate("Dialog", "..."))
        self.label_data.setText(_translate("Dialog", "Data:"))
        self.pushButton_predict.setText(_translate("Dialog", "Train"))
        self.pushButton_save_model.setText(_translate("Dialog", "Save Model"))

